MySQL 도커 구동 및 테이블 초기화 연동
itslaves/rentalgames-starter pull request #3
Opened 2019-05-03 14:56 UTC by skyoo2003

관련 이슈: https://github.com/itslaves/starterpack/issues/2

2019-05-06 05:47 UTC, freddieyyh approved these changes
굳굳

2019-05-06 06:07 UTC, freddieyyh commented
@skyoo2003 승인했는데, 하나 눈에띄어서 적어요ㅋㅋ 
mysql관련 도커 컨테이너인데 이름이 rental_games로 되어있어서. rental_games_mysql정도로 구분하면 좋을것같아요 ㅋㅋ

2019-05-06 06:27 UTC, skyoo2003 commented
@freddieyyh

오 그렇네여 수정할게영

2019-05-09 10:33 UTC, hayden-han requested changes
sql 쿼리문을 모은 파일도 포함하게 수정을 부탁드립니다 👍

2019-05-09 15:05 UTC, skyoo2003 commented
@haninkyu 

리뷰 내용 반영했습니다.

2019-05-09 16:05 UTC, hayden-han approved these changes
수고하셨슴돠

2019-05-09 22:21 UTC, merged