redis 컨테이너 추가
itslaves/rentalgames-starter pull request #7
Opened 2019-06-07 16:06 UTC by freddieyyh

redis 컨테이너 추가했습니다.
data디렉터리 dummy.rdb는 실제 서버 개발하면서 형태가 정해지면 데이터 추가해봐요.

2019-06-07 23:37 UTC, skyoo2003 approved these changes
굳!

2019-06-07 23:40 UTC, skyoo2003 commented
@freddieyyh 아참! README.md 에 make redis 로 단독 구동하는 예제도 추가해주세여 ㅎㅎ

2019-06-08 01:23 UTC, hayden-han requested changes
굳굳 성규리뷰처럼 README.md에 구동하는 커맨드 추가만 해주셈 👍

2019-06-08 02:24 UTC, skyoo2003 commented
Resolves https://github.com/itslaves/rentalgames-starter/issues/1

2019-06-10 01:00 UTC, hayden-han approved these changes

2019-06-10 01:02 UTC, merged

2019-06-10 01:04 UTC, freddieyyh commented
closed #1